[build]
  base = "."
  command = "npm install && npx vite build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
